name: Test T3pio

on:
  push:
    branches: [ test_githubaction ]
  pull_request:
    branches: [ test_githubaction ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java (required for Nextflow)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies for Singularity
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libseccomp-dev \
            pkg-config \
            squashfs-tools \
            cryptsetup \
            wget \
            uidmap \
            git \
            libglib2.0-dev \
            libfuse3-dev \
            libgpgme-dev \
            libssl-dev \
            golang-go

      - name: Install Singularity
        run: |
          export VERSION=3.11.4
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
          tar -xzf singularity-${VERSION}.tar.gz
          cd singularity-${VERSION}
          ./mconfig
          make -C builddir
          sudo make -C builddir install
          singularity --version

      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run test pipeline
        shell: bash -l {0}  # if needed for conda; otherwise can use just "bash"
        run: |
          nextflow run main.nf -profile singularity \
            --input toy_data/reads \
            --run_compare_primers false \
            --contig_file toy_data/contigs \
            --outdir test

